darkroom_app:
    resource: "@DarkroomAppBundle/Controller/"
    type:     annotation
    prefix:   /

darkroom_chemistry:
    resource: "@DarkroomAppBundle/Controller/Chemistry"
    type:     annotation
    prefix:   /chemistry/

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
