darkroom_app:
    resource: "@DarkroomAppBundle/Controller/"
    type:     annotation
    prefix:   /

darkroom_chemistry:
    resource: "@DarkroomAppBundle/Controller/Chemistry"
    type:     annotation
    prefix:   /chemistry/
