services:
  Darkroom.model.manager.unitCategory:
    class: Darkroom\ModelBundle\EntityManager\BaseEntityManager
    arguments:
      - @doctrine.orm.default_entity_manager
      - @form.factory
      - @request
      - "DarkroomModelBundle:Chemistry\UnitCategory"
      - "Darkroom\ModelBundle\Form\Chemistry\UnitCategoryType"
    scope: request

  Darkroom.model.manager.unit:
    class: Darkroom\ModelBundle\EntityManager\BaseEntityManager
    arguments:
      - @doctrine.orm.default_entity_manager
      - @form.factory
      - @request
      - "DarkroomModelBundle:Chemistry\Unit"
      - "Darkroom\ModelBundle\Form\Chemistry\UnitType"
    scope: request

  Darkroom.model.manager.manufacturer:
    class: Darkroom\ModelBundle\EntityManager\BaseEntityManager
    arguments:
      - @doctrine.orm.default_entity_manager
      - @form.factory
      - @request
      - "DarkroomModelBundle:Chemistry\Manufacturer"
      - "Darkroom\ModelBundle\Form\Chemistry\ManufacturerType"
    scope: request

  Darkroom.model.manager.chemical_product:
    class: Darkroom\ModelBundle\EntityManager\BaseEntityManager
    arguments:
      - @doctrine.orm.default_entity_manager
      - @form.factory
      - @request
      - "DarkroomModelBundle:Chemistry\ChemicalProduct"
      - "Darkroom\ModelBundle\Form\Chemistry\ChemicalProductType"
    scope: request

  Darkroom.model.manager.chemical_recipe:
    class: Darkroom\ModelBundle\EntityManager\BaseEntityManager
    arguments:
      - @doctrine.orm.default_entity_manager
      - @form.factory
      - @request
      - "DarkroomModelBundle:Chemistry\ChemicalRecipe"
      - "Darkroom\ModelBundle\Form\Chemistry\ChemicalRecipeType"
    scope: request

  Darkroom.model.manager.chemical_solution:
    class: Darkroom\ModelBundle\EntityManager\BaseEntityManager
    arguments:
      - @doctrine.orm.default_entity_manager
      - @form.factory
      - @request
      - "DarkroomModelBundle:Chemistry\ChemicalSolution"
      - "Darkroom\ModelBundle\Form\Chemistry\ChemicalSolutionType"
    scope: request

  Darkroom.model.manager.recipe_category:
    class: Darkroom\ModelBundle\EntityManager\BaseEntityManager
    arguments:
      - @doctrine.orm.default_entity_manager
      - @form.factory
      - @request
      - "DarkroomModelBundle:Chemistry\RecipeCategory"
      - "Darkroom\ModelBundle\Form\Chemistry\RecipeCategoryType"
    scope: request

  Darkroom.model.manager.solution_container:
    class: Darkroom\ModelBundle\EntityManager\BaseEntityManager
    arguments:
      - @doctrine.orm.default_entity_manager
      - @form.factory
      - @request
      - "DarkroomModelBundle:Chemistry\SolutionContainer"
      - "Darkroom\ModelBundle\Form\Chemistry\SolutionContainerType"
    scope: request