services:
  Darkroom.model.manager.unitCategory:
    class: Darkroom\ModelBundle\EntityManager\BaseEntityManager
    arguments:
      - @doctrine.orm.default_entity_manager
      - @form.factory
      - @request
      - "DarkroomModelBundle:UnitCategory"
      - "Darkroom\ModelBundle\Form\UnitCategoryType"
    scope: request

  Darkroom.model.manager.unit:
    class: Darkroom\ModelBundle\EntityManager\BaseEntityManager
    arguments:
      - @doctrine.orm.default_entity_manager
      - @form.factory
      - @request
      - "DarkroomModelBundle:Unit"
      - "Darkroom\ModelBundle\Form\UnitType"
    scope: request

  Darkroom.model.manager.manufacturer:
    class: Darkroom\ModelBundle\EntityManager\BaseEntityManager
    arguments:
      - @doctrine.orm.default_entity_manager
      - @form.factory
      - @request
      - "DarkroomModelBundle:Manufacturer"
      - "Darkroom\ModelBundle\Form\ManufacturerType"
    scope: request

  Darkroom.model.manager.chemical_product:
    class: Darkroom\ModelBundle\EntityManager\BaseEntityManager
    arguments:
      - @doctrine.orm.default_entity_manager
      - @form.factory
      - @request
      - "DarkroomModelBundle:ChemicalProduct"
      - "Darkroom\ModelBundle\Form\ChemicalProductType"
    scope: request

  Darkroom.model.manager.chemical_recipe:
    class: Darkroom\ModelBundle\EntityManager\BaseEntityManager
    arguments:
      - @doctrine.orm.default_entity_manager
      - @form.factory
      - @request
      - "DarkroomModelBundle:ChemicalRecipe"
      - "Darkroom\ModelBundle\Form\ChemicalRecipeType"
    scope: request

  Darkroom.model.manager.chemical_solution:
    class: Darkroom\ModelBundle\EntityManager\BaseEntityManager
    arguments:
      - @doctrine.orm.default_entity_manager
      - @form.factory
      - @request
      - "DarkroomModelBundle:ChemicalSolution"
      - "Darkroom\ModelBundle\Form\ChemicalSolutionType"
    scope: request

  Darkroom.model.manager.recipe_category:
    class: Darkroom\ModelBundle\EntityManager\BaseEntityManager
    arguments:
      - @doctrine.orm.default_entity_manager
      - @form.factory
      - @request
      - "DarkroomModelBundle:RecipeCategory"
      - "Darkroom\ModelBundle\Form\RecipeCategoryType"
    scope: request

  Darkroom.model.manager.solution_container:
    class: Darkroom\ModelBundle\EntityManager\BaseEntityManager
    arguments:
      - @doctrine.orm.default_entity_manager
      - @form.factory
      - @request
      - "DarkroomModelBundle:"
      - "Darkroom\ModelBundle\Form\SolutionContainerType"
    scope: request