parameters:
    darkroom.default.domainmanager.class: Darkroom\ModelBundle\DomainManager\DefaultDomainManager
    darkroom.default.formhandler.class: Darkroom\ModelBundle\FormHandler\DefaultFormHandler

    darkroom.unitcategory.type.class: Darkroom\ModelBundle\Form\Chemistry\UnitCategoryType
    darkroom.unitcategory.model.class: Darkroom\ModelBundle\Entity\Chemistry\UnitCategory
    darkroom.unit.type.class: Darkroom\ModelBundle\Form\Chemistry\UnitType
    darkroom.unit.model.class: Darkroom\ModelBundle\Entity\Chemistry\Unit
    darkroom.manufacturer.type.class: Darkroom\ModelBundle\Form\Chemistry\ManufacturerType
    darkroom.manufacturer.model.class: Darkroom\ModelBundle\Entity\Chemistry\Manufacturer
    darkroom.recipecategory.type.class: Darkroom\ModelBundle\Form\Chemistry\RecipeCategoryType
    darkroom.recipecategory.model.class: Darkroom\ModelBundle\Entity\Chemistry\RecipeCategory
    darkroom.chemicalproduct.type.class: Darkroom\ModelBundle\Form\Chemistry\ChemicalProductType
    darkroom.chemicalproduct.model.class: Darkroom\ModelBundle\Entity\Chemistry\ChemicalProduct
    darkroom.solutioncontainer.type.class: Darkroom\ModelBundle\Form\Chemistry\SolutionContainerType
    darkroom.solutioncontainer.model.class: Darkroom\ModelBundle\Entity\Chemistry\SolutionContainer
    darkroom.chemicalrecipe.type.class: Darkroom\ModelBundle\Form\Chemistry\ChemicalRecipeType
    darkroom.chemicalrecipe.model.class: Darkroom\ModelBundle\Entity\Chemistry\ChemicalRecipe
    darkroom.chemicalrecipe.formhandler.class: Darkroom\ModelBundle\FormHandler\ChemicalRecipeFormHandler
    darkroom.chemicalrecipe.domainmanager.class: Darkroom\ModelBundle\DomainManager\ChemicalRecipeDomainManager
    darkroom.recipecomponent.domainmanager.class: Darkroom\ModelBundle\DomainManager\RecipeComponentDomainManager


services:

# Unit Category
  darkroom.unitcategory.form.type:
      class: %darkroom.unitcategory.type.class%
      arguments: [%darkroom.unitcategory.model.class%]
      tags:
          - { name: form.type , alias: darkroom_modelbundle_unitCategory }

  darkroom.unitcategory.form:
      class: Symfony\Component\Form\Form
      arguments: ["@darkroom.unitcategory.form.type"]
      factory_method: create
      factory_service: form.factory

  darkroom.unitcategory.form.handler:
      class: %darkroom.default.formhandler.class%
      scope: request
      arguments: ["@darkroom.unitcategory.form", "@request","@darkroom.unitcategory.domainmanager"]

  darkroom.unitcategory.domainmanager:
      class: %darkroom.default.domainmanager.class%
      arguments:
        - @doctrine.orm.default_entity_manager
        - "DarkroomModelBundle:Chemistry\UnitCategory"

# Unit
  darkroom.unit.form.type:
      class: %darkroom.unit.type.class%
      arguments: [%darkroom.unit.model.class%]
      tags:
          - { name: form.type , alias: darkroom_modelbundle_unit }

  darkroom.unit.form:
      class: Symfony\Component\Form\Form
      arguments: ["@darkroom.unit.form.type"]
      factory_method: create
      factory_service: form.factory

  darkroom.unit.form.handler:
      class: %darkroom.default.formhandler.class%
      scope: request
      arguments: ["@darkroom.unit.form", "@request","@darkroom.unit.domainmanager"]

  darkroom.unit.domainmanager:
      class: %darkroom.default.domainmanager.class%
      arguments:
        - @doctrine.orm.default_entity_manager
        - "DarkroomModelBundle:Chemistry\Unit"

# Manufacturer
  darkroom.manufacturer.form.type:
      class: %darkroom.manufacturer.type.class%
      arguments: [%darkroom.manufacturer.model.class%]
      tags:
          - { name: form.type , alias: darkroom_modelbundle_manufacturer }

  darkroom.manufacturer.form:
      class: Symfony\Component\Form\Form
      arguments: ["@darkroom.manufacturer.form.type"]
      factory_method: create
      factory_service: form.factory

  darkroom.manufacturer.form.handler:
      class: %darkroom.default.formhandler.class%
      scope: request
      arguments: ["@darkroom.manufacturer.form", "@request","@darkroom.manufacturer.domainmanager"]

  darkroom.manufacturer.domainmanager:
      class: %darkroom.default.domainmanager.class%
      arguments:
        - @doctrine.orm.default_entity_manager
        - "DarkroomModelBundle:Chemistry\Manufacturer"

# Recipe category
  darkroom.recipecategory.form.type:
      class: %darkroom.recipecategory.type.class%
      arguments: [%darkroom.recipecategory.model.class%]
      tags:
          - { name: form.type , alias: darkroom_modelbundle_recipecategory }

  darkroom.recipecategory.form:
      class: Symfony\Component\Form\Form
      arguments: ["@darkroom.recipecategory.form.type"]
      factory_method: create
      factory_service: form.factory

  darkroom.recipecategory.form.handler:
      class: %darkroom.default.formhandler.class%
      scope: request
      arguments: ["@darkroom.recipecategory.form", "@request","@darkroom.recipecategory.domainmanager"]

  darkroom.recipecategory.domainmanager:
      class: %darkroom.default.domainmanager.class%
      arguments:
        - @doctrine.orm.default_entity_manager
        - "DarkroomModelBundle:Chemistry\RecipeCategory"

# Chemical products
  darkroom.chemicalproduct.form.type:
      class: %darkroom.chemicalproduct.type.class%
      arguments: [%darkroom.chemicalproduct.model.class%]
      tags:
          - { name: form.type , alias: darkroom_modelbundle_chemicalproduct }

  darkroom.chemicalproduct.form:
      class: Symfony\Component\Form\Form
      arguments: ["@darkroom.chemicalproduct.form.type"]
      factory_method: create
      factory_service: form.factory

  darkroom.chemicalproduct.form.handler:
      class: %darkroom.default.formhandler.class%
      scope: request
      arguments: ["@darkroom.chemicalproduct.form", "@request","@darkroom.chemicalproduct.domainmanager"]

  darkroom.chemicalproduct.domainmanager:
      class: %darkroom.default.domainmanager.class%
      arguments:
        - @doctrine.orm.default_entity_manager
        - "DarkroomModelBundle:Chemistry\ChemicalProduct"

# Solution Container
  darkroom.solutioncontainer.form.type:
      class: %darkroom.solutioncontainer.type.class%
      arguments: [%darkroom.solutioncontainer.model.class%]
      tags:
          - { name: form.type , alias: darkroom_modelbundle_solutioncontainer }

  darkroom.solutioncontainer.form:
      class: Symfony\Component\Form\Form
      arguments: ["@darkroom.solutioncontainer.form.type"]
      factory_method: create
      factory_service: form.factory

  darkroom.solutioncontainer.form.handler:
      class: %darkroom.default.formhandler.class%
      scope: request
      arguments: ["@darkroom.solutioncontainer.form", "@request","@darkroom.solutioncontainer.domainmanager"]

  darkroom.solutioncontainer.domainmanager:
      class: %darkroom.default.domainmanager.class%
      arguments:
        - @doctrine.orm.default_entity_manager
        - "DarkroomModelBundle:Chemistry\SolutionContainer"

# Chemical recipe
  darkroom.chemicalrecipe.form.type:
      class: %darkroom.chemicalrecipe.type.class%
      arguments: [%darkroom.chemicalrecipe.model.class%]
      tags:
          - { name: form.type , alias: darkroom_modelbundle_chemicalrecipe }

  darkroom.chemicalrecipe.form:
      class: Symfony\Component\Form\Form
      arguments: ["@darkroom.chemicalrecipe.form.type"]
      factory_method: create
      factory_service: form.factory

  darkroom.chemicalrecipe.form.handler:
      class: %darkroom.chemicalrecipe.formhandler.class%
      scope: request
      arguments:
        - "@darkroom.chemicalrecipe.form"
        - "@request"
        - "@darkroom.chemicalrecipe.domainmanager"
        - "@darkroom.recipecomponent.domainmanager"

  darkroom.chemicalrecipe.domainmanager:
      class: %darkroom.chemicalrecipe.domainmanager.class%
      arguments:
        - @doctrine.orm.default_entity_manager
        - @darkroom.recipecomponent.domainmanager
        - "DarkroomModelBundle:Chemistry\ChemicalRecipe"

  darkroom.recipecomponent.domainmanager:
        class: %darkroom.recipecomponent.domainmanager.class%
        arguments:
          - @doctrine.orm.default_entity_manager
          - "DarkroomModelBundle:Chemistry\RecipeComponent"

