parameters:
    darkroom.default.entitymanager.class: Darkroom\ModelBundle\EntityManager\DefaultEntityManager
    darkroom.default.formhandler.class: Darkroom\ModelBundle\FormHandler\DefaultFormHandler

    darkroom.unitcategory.type.class: Darkroom\ModelBundle\Form\Chemistry\UnitCategoryType
    darkroom.unitcategory.model.class: Darkroom\ModelBundle\Entity\Chemistry\UnitCategory
    darkroom.unit.type.class: Darkroom\ModelBundle\Form\Chemistry\UnitType
    darkroom.unit.model.class: Darkroom\ModelBundle\Entity\Chemistry\Unit
    darkroom.manufacturer.type.class: Darkroom\ModelBundle\Form\Chemistry\ManufacturerType
    darkroom.manufacturer.model.class: Darkroom\ModelBundle\Entity\Chemistry\Manufacturer
    darkroom.recipecategory.type.class: Darkroom\ModelBundle\Form\Chemistry\RecipeCategoryType
    darkroom.recipecategory.model.class: Darkroom\ModelBundle\Entity\Chemistry\RecipeCategory
    darkroom.chemicalproduct.type.class: Darkroom\ModelBundle\Form\Chemistry\ChemicalProductType
    darkroom.chemicalproduct.model.class: Darkroom\ModelBundle\Entity\Chemistry\ChemicalProduct


services:

# Unit Category
  darkroom.unitcategory.form.type:
      class: %darkroom.unitcategory.type.class%
      arguments: [%darkroom.unitcategory.model.class%]
      tags:
          - { name: form.type , alias: darkroom_modelbundle_unitCategory }

  darkroom.unitcategory.form:
      class: Symfony\Component\Form\Form
      arguments: ["@darkroom.unitcategory.form.type"]
      factory_method: create
      factory_service: form.factory

  darkroom.unitcategory.form.handler:
      class: %darkroom.default.formhandler.class%
      scope: request
      arguments: ["@darkroom.unitcategory.form", "@request","@darkroom.unitcategory.entitymanager"]

  darkroom.unitcategory.entitymanager:
      class: %darkroom.default.entitymanager.class%
      arguments:
        - @doctrine.orm.default_entity_manager
        - "DarkroomModelBundle:Chemistry\UnitCategory"

# Unit
  darkroom.unit.form.type:
      class: %darkroom.unit.type.class%
      arguments: [%darkroom.unit.model.class%]
      tags:
          - { name: form.type , alias: darkroom_modelbundle_unit }

  darkroom.unit.form:
      class: Symfony\Component\Form\Form
      arguments: ["@darkroom.unit.form.type"]
      factory_method: create
      factory_service: form.factory

  darkroom.unit.form.handler:
      class: %darkroom.default.formhandler.class%
      scope: request
      arguments: ["@darkroom.unit.form", "@request","@darkroom.unit.entitymanager"]

  darkroom.unit.entitymanager:
      class: %darkroom.default.entitymanager.class%
      arguments:
        - @doctrine.orm.default_entity_manager
        - "DarkroomModelBundle:Chemistry\Unit"

# Manufacturer
  darkroom.manufacturer.form.type:
      class: %darkroom.manufacturer.type.class%
      arguments: [%darkroom.manufacturer.model.class%]
      tags:
          - { name: form.type , alias: darkroom_modelbundle_manufacturer }

  darkroom.manufacturer.form:
      class: Symfony\Component\Form\Form
      arguments: ["@darkroom.manufacturer.form.type"]
      factory_method: create
      factory_service: form.factory

  darkroom.manufacturer.form.handler:
      class: %darkroom.default.formhandler.class%
      scope: request
      arguments: ["@darkroom.manufacturer.form", "@request","@darkroom.manufacturer.entitymanager"]

  darkroom.manufacturer.entitymanager:
      class: %darkroom.default.entitymanager.class%
      arguments:
        - @doctrine.orm.default_entity_manager
        - "DarkroomModelBundle:Chemistry\Manufacturer"

# Recipe category
  darkroom.recipecategory.form.type:
      class: %darkroom.recipecategory.type.class%
      arguments: [%darkroom.recipecategory.model.class%]
      tags:
          - { name: form.type , alias: darkroom_modelbundle_recipecategory }

  darkroom.recipecategory.form:
      class: Symfony\Component\Form\Form
      arguments: ["@darkroom.recipecategory.form.type"]
      factory_method: create
      factory_service: form.factory

  darkroom.recipecategory.form.handler:
      class: %darkroom.default.formhandler.class%
      scope: request
      arguments: ["@darkroom.recipecategory.form", "@request","@darkroom.recipecategory.entitymanager"]

  darkroom.recipecategory.entitymanager:
      class: %darkroom.default.entitymanager.class%
      arguments:
        - @doctrine.orm.default_entity_manager
        - "DarkroomModelBundle:Chemistry\RecipeCategory"

# Chemical products
  darkroom.chemicalproduct.form.type:
      class: %darkroom.chemicalproduct.type.class%
      arguments: [%darkroom.chemicalproduct.model.class%]
      tags:
          - { name: form.type , alias: darkroom_modelbundle_chemicalproduct }

  darkroom.chemicalproduct.form:
      class: Symfony\Component\Form\Form
      arguments: ["@darkroom.chemicalproduct.form.type"]
      factory_method: create
      factory_service: form.factory

  darkroom.chemicalproduct.form.handler:
      class: %darkroom.default.formhandler.class%
      scope: request
      arguments: ["@darkroom.chemicalproduct.form", "@request","@darkroom.chemicalproduct.entitymanager"]

  darkroom.chemicalproduct.entitymanager:
      class: %darkroom.default.entitymanager.class%
      arguments:
        - @doctrine.orm.default_entity_manager
        - "DarkroomModelBundle:Chemistry\ChemicalProduct"